##sub>0.75で多数決、ただしsub12とsub31の値が一致していた場合sub12とsub31の値が優先される

In [1]:
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).

In [2]:
import pandas as pd
import numpy as np
import os

In [3]:
INPUT_DIR = '/content/drive/MyDrive/Competitions/Signate/Student Cup 2022/input/'
OUTPUT_DIR = '/content/drive/MyDrive/Competitions/Signate/Student Cup 2022/output/'
OUTPUT_SUB_DIR = os.path.join(OUTPUT_DIR,'Submission')

In [4]:
sub10 = pd.read_csv(os.path.join(OUTPUT_SUB_DIR,"7327submission10.csv"),header=None)
sub10.columns = ["id","sub10"]
sub12 = pd.read_csv(os.path.join(OUTPUT_SUB_DIR,"7455submission12.csv"),header=None)
sub12.columns = ["id","sub12"]
sub16 = pd.read_csv(os.path.join(OUTPUT_SUB_DIR,"7385submission16.csv"),header=None)
sub16.columns = ["id","sub16"]
sub20 = pd.read_csv(os.path.join(OUTPUT_SUB_DIR,"7301submission20.csv"),header=None)
sub20.columns = ["id","sub20"]
sub21 = pd.read_csv(os.path.join(OUTPUT_SUB_DIR,"7525submission21.csv"),header=None)
sub21.columns = ["id","sub21"]
sub22 = pd.read_csv(os.path.join(OUTPUT_SUB_DIR,"0.7473submission22[2+3+5].csv"),header=None)
sub22.columns = ["id","sub22"]
sub24 = pd.read_csv(os.path.join(OUTPUT_SUB_DIR,"7347submission24.csv"),header=None)
sub24.columns = ["id","sub24"]
sub26 = pd.read_csv(os.path.join(OUTPUT_SUB_DIR,"8107submission26.csv"),header=None)
sub26.columns = ["id","sub26"]
sub27 = pd.read_csv(os.path.join(OUTPUT_SUB_DIR,"7150submission27.csv"),header=None)
sub27.columns = ["id","sub27"]
sub28 = pd.read_csv(os.path.join(OUTPUT_SUB_DIR,"7460submission28.csv"),header=None)
sub28.columns = ["id","sub28"]
sub30 = pd.read_csv(os.path.join(OUTPUT_SUB_DIR,"???submission30.csv"),header=None)
sub30.columns = ["id","sub30"]
sub31 = pd.read_csv(os.path.join(OUTPUT_SUB_DIR,"7429submission31.csv"),header=None)
sub31.columns = ["id","sub31"]
sub32 = pd.read_csv(os.path.join(OUTPUT_SUB_DIR,"submission32_Stacking.csv"),header=None)
sub32.columns = ["id","sub32"]
sub33 = pd.read_csv(os.path.join(OUTPUT_SUB_DIR,"submission33 ensemble[12+30+31].csv"),header=None)
sub33.columns = ["id","sub33"]
sub34 = pd.read_csv(os.path.join(OUTPUT_SUB_DIR,"submission34ensemble[12+31].csv"),header=None)
sub34.columns = ["id","sub34"]

In [5]:
df = sub10.merge(sub12,how='left',on='id').merge(sub16,how='left',on='id').merge(sub20,how='left',on='id').merge(sub21,how='left',on='id').merge(sub22,how='left',on='id').merge(sub24,how='left',on='id').merge(sub26,how='left',on='id').merge(sub27,how='left',on='id').merge(sub28,how='left',on='id').merge(sub30,how='left',on='id').merge(sub31,how='left',on='id').merge(sub32,how='left',on='id').merge(sub33,how='left',on='id').merge(sub34,how='left',on='id')

In [6]:
df

,id,sub10,sub12,sub16,sub20,sub21,sub22,sub24,sub26,sub27,sub28,sub30,sub31,sub32,sub33,sub34
0,1516,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1
1,1517,4,4,4,4,4,4,4,4,4,4,4,4,4,4,4
2,1518,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3
3,1519,4,4,4,4,4,4,4,4,4,4,4,4,4,4,4
4,1520,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1512,3028,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3
1513,3029,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1
1514,3030,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3
1515,3031,4,1,1,4,1,4,4,4,4,1,1,4,4,1,1
1516,3032,3,1,1,3,3,1,3,1,1,3,4,1,3,1,1

In [7]:
df["label"] = df.loc[:,"sub10":].mode(axis=1)[0]
df["label"] = df["label"].astype("int")
df["relabel"] = df["label"]
df.loc[df.sub12==df.sub31,"relabel"] = df.sub31
df

,id,sub10,sub12,sub16,sub20,sub21,sub22,sub24,sub26,sub27,sub28,sub30,sub31,sub32,sub33,sub34,label,relabel
0,1516,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1
1,1517,4,4,4,4,4,4,4,4,4,4,4,4,4,4,4,4,4
2,1518,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3
3,1519,4,4,4,4,4,4,4,4,4,4,4,4,4,4,4,4,4
4,1520,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1512,3028,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3
1513,3029,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1
1514,3030,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3
1515,3031,4,1,1,4,1,4,4,4,4,1,1,4,4,1,1,4,4
1516,3032,3,1,1,3,3,1,3,1,1,3,4,1,3,1,1,1,1

In [8]:
df.head(30)

,id,sub10,sub12,sub16,sub20,sub21,sub22,sub24,sub26,sub27,sub28,sub30,sub31,sub32,sub33,sub34,label,relabel
0,1516,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1
1,1517,4,4,4,4,4,4,4,4,4,4,4,4,4,4,4,4,4
2,1518,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3
3,1519,4,4,4,4,4,4,4,4,4,4,4,4,4,4,4,4,4
4,1520,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3
5,1521,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1
6,1522,2,2,1,2,2,2,2,2,2,2,1,2,1,2,2,2,2
7,1523,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3
8,1524,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1
9,1525,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3
10,1526,4,4,4,4,4,4,4,4,4,4,4,4,4,4,4,4,4
11,1527,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2
12,1528,4,4,4,4,4,4,4,4,4,1,4,4,4,4,4,4,4
13,1529,4,4,4,4,4,4,4,4,4,4,4,4,4,4,4,4,4
14,1530,4,4,4,4,4,4,4,4,4,4,4,4,4,4,4,4,4
15,1531,1,1,1,1,1,1,1,1,1,1,4,4,1,4,1,1,1
16,1532,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1
17,1533,4,4,4,4,4,4,4,4,4,4,4,4,4,4,4,4,4
18,1534,4,4,4,4,4,4,4,4,4,4,4,4,4,4,4,4,4
19,1535,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3
20,1536,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3
21,1537,4,4,4,1,4,4,4,4,4,1,4,4,4,4,4,4,4
22,1538,4,4,4,4,4,4,4,4,4,4,4,4,4,4,4,4,4
23,1539,1,1,1,2,1,1,1,1,1,1,1,1,1,1,1,1,1
24,1540,2,2,2,1,1,2,1,1,1,1,1,1,1,1,2,1,1
25,1541,4,4,4,4,4,4,4,4,4,4,4,4,4,4,4,4,4
26,1542,4,4,4,4,4,4,4,4,4,4,4,4,4,4,4,4,4
27,1543,1,2,2,1,1,1,1,1,1,1,2,2,1,2,2,1,2
28,1544,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3
29,1545,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1

In [9]:
df.tail(30)

,id,sub10,sub12,sub16,sub20,sub21,sub22,sub24,sub26,sub27,sub28,sub30,sub31,sub32,sub33,sub34,label,relabel
1487,3003,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3
1488,3004,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3
1489,3005,3,1,3,3,3,3,3,3,1,3,1,1,3,1,1,3,1
1490,3006,4,4,4,1,4,4,4,4,4,1,4,4,4,4,4,4,4
1491,3007,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1
1492,3008,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3
1493,3009,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3
1494,3010,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3
1495,3011,1,1,1,1,1,1,1,1,1,1,1,4,1,1,1,1,1
1496,3012,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1
1497,3013,4,4,4,4,4,4,4,4,4,4,4,4,4,4,4,4,4
1498,3014,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3
1499,3015,4,4,4,4,4,4,4,4,4,4,4,4,4,4,4,4,4
1500,3016,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1
1501,3017,1,1,4,4,4,1,1,4,4,1,4,1,4,1,1,1,1
1502,3018,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3
1503,3019,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3
1504,3020,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1
1505,3021,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3
1506,3022,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3
1507,3023,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3
1508,3024,4,4,4,4,4,4,4,4,4,4,4,4,4,4,4,4,4
1509,3025,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3
1510,3026,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1
1511,3027,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3
1512,3028,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3
1513,3029,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1
1514,3030,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3
1515,3031,4,1,1,4,1,4,4,4,4,1,1,4,4,1,1,4,4
1516,3032,3,1,1,3,3,1,3,1,1,3,4,1,3,1,1,1,1

In [10]:
display(df.loc[df.label!=df.relabel])
print(len(df.loc[df.label!=df.relabel]))

,id,sub10,sub12,sub16,sub20,sub21,sub22,sub24,sub26,sub27,sub28,sub30,sub31,sub32,sub33,sub34,label,relabel
27,1543,1,2,2,1,1,1,1,1,1,1,2,2,1,2,2,1,2
77,1593,1,4,4,1,1,1,1,1,4,1,4,4,1,4,4,1,4
269,1785,2,3,2,2,2,2,2,2,1,1,3,3,3,3,3,2,3
780,2296,3,2,3,3,3,3,3,3,2,3,2,2,3,2,2,3,2
916,2432,4,1,4,4,4,4,4,4,4,4,4,1,4,4,1,4,1
919,2435,4,1,4,4,4,4,1,4,4,4,1,1,4,1,1,4,1
997,2513,1,4,4,1,1,1,1,1,4,1,4,4,1,4,4,1,4
1036,2552,1,2,2,1,1,1,1,1,2,1,1,2,1,2,2,1,2
1043,2559,3,4,3,3,3,3,3,4,4,1,4,4,3,4,4,3,4
1052,2568,3,1,3,3,3,3,3,3,3,3,1,1,3,1,1,3,1
1126,2642,3,1,3,3,3,3,3,3,1,3,1,1,3,1,1,3,1
1225,2741,1,2,1,1,1,1,1,1,2,1,1,2,1,2,2,1,2
1252,2768,2,2,3,3,3,3,3,2,3,3,2,2,3,2,2,3,2
1276,2792,2,1,1,2,2,2,2,2,2,2,2,1,1,2,1,2,1
1471,2987,3,4,3,3,3,3,3,3,4,3,4,4,3,4,4,3,4
1489,3005,3,1,3,3,3,3,3,3,1,3,1,1,3,1,1,3,1

16

In [11]:
display(df.loc[df.sub12!=df.sub31])
print(len(df.loc[df.sub12!=df.sub31]))

,id,sub10,sub12,sub16,sub20,sub21,sub22,sub24,sub26,sub27,sub28,sub30,sub31,sub32,sub33,sub34,label,relabel
15,1531,1,1,1,1,1,1,1,1,1,1,4,4,1,4,1,1,1
24,1540,2,2,2,1,1,2,1,1,1,1,1,1,1,1,2,1,1
66,1582,1,2,1,2,2,1,1,1,1,2,2,1,1,2,2,1,1
69,1585,1,1,4,1,1,1,1,4,4,1,4,4,4,4,1,1,1
111,1627,3,4,1,1,1,1,3,1,4,1,3,1,4,4,1,1,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1446,2962,3,3,3,3,3,3,3,3,1,3,3,1,3,3,3,3,3
1451,2967,4,1,4,4,4,4,4,4,4,4,4,4,4,4,4,4,4
1479,2995,4,1,4,4,4,4,4,4,4,4,4,4,4,4,4,4,4
1495,3011,1,1,1,1,1,1,1,1,1,1,1,4,1,1,1,1,1
1515,3031,4,1,1,4,1,4,4,4,4,1,1,4,4,1,1,4,4

97

In [12]:
df[["id","relabel"]].to_csv(os.path.join(OUTPUT_SUB_DIR,"final_submission多数決.csv"),index=False,header=False)

In [13]:
df[["id","relabel"]]

        id  relabel
0     1516        1
1     1517        4
2     1518        3
3     1519        4
4     1520        3
...    ...      ...
1512  3028        3
1513  3029        1
1514  3030        3
1515  3031        4
1516  3032        1

[1517 rows x 2 columns]

In [14]:
dup_test_ids = [1707,2122,2291,2775,2191,1700,2304,2149,2676,2844,2144,2764,1774,2446,2736,2301,1822,1852,2070,1609,2423,2695,
                2077,2409,2233,2076,1568,3001,1662,1997, 2896,2352,2842,2321,1630,2259,2968,1551, 1673, 2168]
df[df["id"].isin(dup_test_ids)]

,id,sub10,sub12,sub16,sub20,sub21,sub22,sub24,sub26,sub27,sub28,sub30,sub31,sub32,sub33,sub34,label,relabel
35,1551,4,4,4,4,4,4,4,4,4,4,4,4,4,4,4,4,4
52,1568,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1
93,1609,4,4,4,4,4,4,4,4,4,4,4,4,4,4,4,4,4
114,1630,4,4,4,4,4,4,4,4,4,4,4,4,4,4,4,4,4
146,1662,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1
157,1673,4,4,4,4,4,4,4,4,4,4,4,4,4,4,4,4,4
184,1700,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1
191,1707,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3
258,1774,4,4,4,4,4,4,4,4,4,4,4,4,4,4,4,4,4
306,1822,4,4,4,4,4,4,4,4,4,4,4,4,4,4,4,4,4
336,1852,4,4,4,4,4,4,4,4,4,4,4,4,4,4,4,4,4
481,1997,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3
554,2070,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3
560,2076,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1
561,2077,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3
606,2122,4,4,4,4,4,4,4,4,4,4,4,4,4,4,4,4,4
628,2144,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3
633,2149,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1
652,2168,4,4,4,4,4,4,4,4,4,4,4,4,4,4,4,4,4
675,2191,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1
717,2233,4,4,4,4,4,4,4,4,4,4,4,4,4,4,4,4,4
743,2259,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1
775,2291,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1
785,2301,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1
788,2304,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1
805,2321,4,4,4,4,4,4,4,4,4,4,4,4,4,4,4,4,4
836,2352,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1
893,2409,4,4,4,4,4,4,4,4,4,4,4,4,4,4,4,4,4
907,2423,4,4,4,4,4,4,4,4,4,4,4,4,4,4,4,4,4
930,2446,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1
1160,2676,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3
1179,2695,4,4,4,4,4,4,4,4,4,4,4,4,4,4,4,4,4
1220,2736,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1
1248,2764,4,4,4,4,4,4,4,4,4,4,4,4,4,4,4,4,4
1259,2775,4,4,4,4,4,4,4,4,4,4,4,4,4,4,4,4,4
1326,2842,4,4,4,4,4,4,4,1,4,4,4,4,4,4,4,4,4
1328,2844,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1
1380,2896,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3
1452,2968,4,4,4,4,4,4,4,4,4,4,4,4,4,4,4,4,4
1485,3001,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1

In [15]:
df[df["id"].isin(dup_test_ids)][["id","relabel"]]

        id  relabel
35    1551        4
52    1568        1
93    1609        4
114   1630        4
146   1662        1
157   1673        4
184   1700        1
191   1707        3
258   1774        4
306   1822        4
336   1852        4
481   1997        3
554   2070        3
560   2076        1
561   2077        3
606   2122        4
628   2144        3
633   2149        1
652   2168        4
675   2191        1
717   2233        4
743   2259        1
775   2291        1
785   2301        1
788   2304        1
805   2321        4
836   2352        1
893   2409        4
907   2423        4
930   2446        1
1160  2676        3
1179  2695        4
1220  2736        1
1248  2764        4
1259  2775        4
1326  2842        4
1328  2844        1
1380  2896        3
1452  2968        4
1485  3001        1

In [16]:
T = pd.DataFrame([[1707,2122,2291,2775,2191,1700,2304,2149,2676,2844,2144,2764,1774,2446,2736,2301,1822,1852,2070,1609,2423,2695,
                2077,2409,2233,2076,1568,3001,1662,1997, 2896,2352,2842,2321,1630,2259,2968,1551, 1673, 2168],
                [3,4,1,4,1,1,1,1,3,1,3,4,4,1,1,1,4,4,3,4,4,4,3,4,4,1,1,1,1,3,3,1,4,4,4,1,4,4,4,4]]).T
T.columns =["id","label"]
T = T.sort_values(by="id")
T

      id  label
37  1551      4
26  1568      1
19  1609      4
34  1630      4
28  1662      1
38  1673      4
5   1700      1
0   1707      3
12  1774      4
16  1822      4
17  1852      4
29  1997      3
18  2070      3
25  2076      1
22  2077      3
1   2122      4
10  2144      3
7   2149      1
39  2168      4
4   2191      1
24  2233      4
35  2259      1
2   2291      1
15  2301      1
6   2304      1
33  2321      4
31  2352      1
23  2409      4
20  2423      4
13  2446      1
8   2676      3
21  2695      4
14  2736      1
11  2764      4
3   2775      4
32  2842      4
9   2844      1
30  2896      3
36  2968      4
27  3001      1